image: mcr.microsoft.com/dotnet/sdk:latest

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH == 'Development'

stages:
  - build
  - test
  
variables:
  USERMICROSERVICE: "./UserMicroservice/UserMicroservice.csproj"
  USERMICROSERVICETESTS: "./UserMicroservice.Test/UserMicroservice.Test.csproj"
  GATEWAY: "./Gateway/Gateway.csproj"
  MAINSOLUTION: "./MusicizeAPI.sln"

B.1_Build_UserMicroservice:
  before_script:
    - "dotnet build -restore $USERMICROSERVICE"
  stage: build
  script:
  - "dotnet build --no-restore $USERMICROSERVICE"

B.2_Build_UserMicroserviceTests:
  before_script:
    - "dotnet build -restore $USERMICROSERVICETESTS"
  stage: build
  needs: [B.1_Build_UserMicroservice]
  script:
  - "dotnet build --no-restore $USERMICROSERVICETESTS"

B.3_Build_Gateway:
  before_script:
    - "dotnet build -restore $GATEWAY"
  stage: build
  needs: [B.1_Build_UserMicroservice, B.2_Build_UserMicroserviceTests]
  script:
  - "dotnet build --no-restore $GATEWAY"

B.4_Build_Solution:
  before_script:
    - "dotnet build -restore $MAINSOLUTION"
  stage: build
  needs: [B.1_Build_UserMicroservice, B.2_Build_UserMicroserviceTests, B.3_Build_Gateway]
  script:
  - "dotnet build --no-restore $MAINSOLUTION"

T.1_Test_UserMicroserviceTests:
  stage: test
  needs: [B.1_Build_UserMicroservice, B.2_Build_UserMicroserviceTests, B.3_Build_Gateway, B.4_Build_Solution]
  script:
  - "dotnet build -restore $USERMICROSERVICETESTS"
  - "dotnet test $USERMICROSERVICETESTS"
