name: development
on:
  push:
    branches: [development]

jobs:
  build: 
    runs-on: self-hosted
    strategy:
      matrix: 
        PATH_TO_SLN_OR_CSPROJ:
          - "./back-end/UserMicroservice/UserMicroservice.csproj"
          - "./back-end/UserMicroservice.Test/UserMicroservice.Test.csproj"
          - "./back-end/Gateway/Gateway.csproj"
          - "./back-end/MusicizeAPI.sln"

    steps:
      - name: Clone repo to runner
        uses: actions/checkout@v3

      - name: build 
        uses: ./.github/actions/back-end/build
        with:
          PATH_TO_SLN_OR_CSPROJ: ${{matrix.PATH_TO_SLN_OR_CSPROJ}}
